version: '3.8'
services:
  database:
    image: postgres:latest
    container_name: team8_database
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432" # 5433 no host, 5432 no contêiner
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - team8_network

  adminer:
    image: adminer
    container_name: team8_adminer
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - database
    networks:
      - team8_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: team8_backend
    ports:
      - "${PORT}:9000" # 3333 no host, 9000 no contêiner
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=9000
      - DB_HOST=database
      - DB_PORT=5432 # Porta interna do PostgreSQL no contêiner
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - database
    networks:
      - team8_network

volumes:
  db-data:

networks:
  team8_network: {}