import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MetaDataLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
        {children}
    </>

  )
}